using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddReferentesCompatibility : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.referentes (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre text NOT NULL,
                    tipo text NOT NULL,
                    activo boolean NOT NULL DEFAULT true,
                    orden integer NOT NULL DEFAULT 0,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT referentes_tipo_check CHECK (tipo IN ('doctor', 'agencia', 'otro'))
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_referentes_nombre_tipo"
                    ON public.referentes (nombre, tipo);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.referentes;
                """);
        }
    }
}
