// <auto-generated />
using MedicalCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MedicalCenterDbContext))]
[Migration("20260421010000_AddConsultationsAndOutOfHours")]
partial class AddConsultationsAndOutOfHours
{
}
