// <auto-generated />
using MedicalCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MedicalCenterDbContext))]
[Migration("20260424140000_AddAppointmentsUpdatedAtCompatibility")]
partial class AddAppointmentsUpdatedAtCompatibility
{
}
