using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddAdminEventFeedCompatibility : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.admin_event_feed (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at timestamp with time zone NOT NULL DEFAULT now(),
                    actor_user_id uuid NULL,
                    actor_label text NOT NULL DEFAULT 'Sistema',
                    action_code text NOT NULL,
                    action_family text NOT NULL,
                    entity_type text NOT NULL,
                    entity_id text NOT NULL,
                    agenda_type text NULL,
                    paciente_id uuid NULL,
                    paciente_nombre text NULL,
                    medico_id integer NULL,
                    medico_nombre text NULL,
                    title text NOT NULL,
                    summary text NOT NULL,
                    source_system text NOT NULL,
                    source_record_key text NOT NULL,
                    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamp with time zone NOT NULL DEFAULT now()
                );

                CREATE INDEX IF NOT EXISTS "IX_admin_event_feed_occurred_at_id"
                    ON public.admin_event_feed (occurred_at DESC, id DESC);

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_admin_event_feed_source_unique"
                    ON public.admin_event_feed (source_system, source_record_key);

                CREATE INDEX IF NOT EXISTS "IX_admin_event_feed_actor_user_id"
                    ON public.admin_event_feed (actor_user_id);

                CREATE INDEX IF NOT EXISTS "IX_admin_event_feed_action_code"
                    ON public.admin_event_feed (action_code);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.admin_event_feed;
                """);
        }
    }
}
