using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddMedicosCompatibility : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.medicos (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre text NOT NULL,
                    activo boolean NOT NULL DEFAULT true,
                    orden integer NOT NULL DEFAULT 0,
                    created_at timestamp with time zone NULL DEFAULT now(),
                    perfil_id uuid NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_medicos_nombre"
                    ON public.medicos (nombre);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.medicos;
                """);
        }
    }
}
