// <auto-generated />
using MedicalCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MedicalCenterDbContext))]
    [Migration("20260420200000_AddLegacyCompatibilityFields")]
    partial class AddLegacyCompatibilityFields
    {
    }
}
