using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations;

public partial class AddCatalogosFaltantes : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS public.condiciones_iva (
                id         integer                  GENERATED BY DEFAULT AS IDENTITY,
                nombre     character varying(200)   NOT NULL,
                activo     boolean                  NOT NULL DEFAULT true,
                orden      integer                  NOT NULL DEFAULT 0,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_condiciones_iva PRIMARY KEY (id)
            );

            CREATE INDEX IF NOT EXISTS ix_condiciones_iva_nombre ON public.condiciones_iva (nombre);

            INSERT INTO public.condiciones_iva (nombre, activo, orden) VALUES
                ('Responsable Inscripto',     true,  1),
                ('Responsable Monotributo',   true,  2),
                ('Exento',                    true,  3),
                ('Consumidor Final',          true,  4),
                ('No Responsable',            true,  5)
            ON CONFLICT DO NOTHING;

            CREATE TABLE IF NOT EXISTS public.dias_laborables_config (
                key           character varying(20)    NOT NULL,
                dias_semana   smallint[]               NOT NULL,
                created_at    timestamp with time zone NOT NULL DEFAULT now(),
                updated_at    timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_dias_laborables_config PRIMARY KEY (key)
            );

            INSERT INTO public.dias_laborables_config (key, dias_semana)
            VALUES ('default', ARRAY[1,2,3,4,5]::smallint[])
            ON CONFLICT DO NOTHING;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS public.dias_laborables_config;
            DROP TABLE IF EXISTS public.condiciones_iva;
            """);
    }
}
