using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicalCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddObrasSocialesCompatibility : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.obras_sociales (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre text NOT NULL,
                    activa boolean NOT NULL DEFAULT true,
                    tiene_convenio boolean NOT NULL DEFAULT false,
                    orden integer NOT NULL DEFAULT 0,
                    created_at timestamp with time zone NULL DEFAULT now(),
                    abreviatura text NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_obras_sociales_nombre"
                    ON public.obras_sociales (nombre);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.obras_sociales;
                """);
        }
    }
}
